config/routes.rb
Rails.application.routes.draw do
    mount Resque::Server, :at => '/resque'
  get 'dradio_widget', to: 'rooms#widget', as: :widget
	get 'available_rooms', to: 'rooms#available_rooms', as: :available_rooms
	root 'rooms#index'
  resources :rooms
 scope module: :users do
        devise_for :users, skip: [:passwords, :registrations]
      end
devise_scope :user do
      get 'auth/login', to: 'users/sessions#custom_login', as: :login
    end
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

		extend FriendlyId
	friendly_id :slug_candidates, use: [:slugged, :finders]

	def slug_candidates
    [
      :name,
      [:name]
    ]
  end


  belongs_to :user
  has_many :room_tags
  has_many :tags, through: :room_tags
# accepts_nested_attributes_for :room_tags, :allow_destroy => true
  validates_presence_of :name, :description
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :widget]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index
    # resource = User.first
    # sign_in(:user, resource)
    # byebug
    @rooms = Room.all
    @room = Room.new
    # @tags = Tag.all.pluck(:name)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    respond_to do |format|
      if @room.save
        #save tags
        save_tags(@room.id)
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
       flash[:warning] = 'Please try again!.' 
       format.html { redirect_to root_path} 
       format.json { render json: @room.errors, status: :unprocessable_entity }
     end
   end
 end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def widget
    @rooms = Room.all
  end


  def save_tags(room_id)
    @room_tags = []
    params[:tags].split(",").each do |tag|
     result =  Tag.find_by_name(tag.downcase)
     if result
      @room_tags << result.id
    else
      new_tag = Tag.create(name: tag.downcase)
      @room_tags << new_tag.id
    end
  end
    @room_tags.map {|tag| RoomTag.create(room_id: room_id, tag_id: tag)}

end

def available_rooms
  @tag = Tag.all
  @rooms = Room.all
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.fetch(:room).permit(:name, :user_id, :description)
    end
  end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="modal-body">
<%= form_with(model: room, local: true) do |form| %>
  <%# if room.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%#= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <%# room.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div> -->
  <%# end %>
<div class="lable">Room Name</div>
<%= form.text_field :name,class: 'form-control', required: true %>

<div class="lable">Room Description</div>
<%= form.text_area :description,class: 'form-control', rows: '10', required: true %>

<div class="lable">Room Tags</div>
<%= text_field_tag 'tags',nil,:multiple => true, class: 'form-control tag_class',required: true , data:{"role": "tagsinput"}%>
</div>

  <div class="modal-footer">
        <button type="button" class="btn btn-danger text-black btn-sm" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-warning text-black btn-sm text-16">Create Room</button>
      </div>
<% end %>

<!-- <iframe frameborder="0" src="https://discordapp.com/widget?id=335703116689440770&amp;theme=light" target="_parent" height="425px" name="" width="100%" style="position: relative; display: block; height: 425px; width: 100%;"></iframe> -->
<!-- <iframe src="https://dradio.rjght.com//dradio_widget" width="300" height="700px" frameborder="0"></iframe> -->

<script type="text/javascript">
$('.tag_class').tagsinput({
  trimValue: true,
    allowDuplicates: false

});

</script>

app/views/rooms/available_rooms.html.erb
<div style="margin-top: 70px; padding-top: 20px;" class="rooms_section">
  <div class="row">
    <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
      <h2 class="section-heading text-40 font-bold text-warning padding-bottom-50 text-center">Popular Live Rooms</h2>
  </div>
</div>
<div class="row">

<div class="col-sm-12 col-xs-12 col-md-3 col-lg-2">

  <h4 style="margin-left: 10px;">All Tags</h4>
<div id="filters" class="button-group set_height" style="overflow: scroll;">
  <% @tag.each do |tag| %>
  <button class="button fil-tag" data-filter=".<%=tag.name%>"><%=tag.name%></button>
  <% end %>
  <button class="button fil-tag" data-filter="*" style="color: #ffbf43;">show all</button>
</div>
</div>
<div class="col-sm-12 col-xs-12 col-md-9 col-lg-10">
<div class="container ">
  <div class="row">
    <div class="col-md-12 mx-auto">
    
      <div class="col-md-12 text-center margin-auto clearfix" id="posts">


        <div class="no_room" style="display: none;">No Room for this tag</div>
        <% @rooms.each do |room|%>
        <%tag_arr = room.tags.collect{|a| a.name}.join(', ').gsub(",", " ")%>
          <div class="col-md-4 pull-left item <%=tag_arr.to_s %>">
            <div class=>
           <a href= <% if user_signed_in? %> "<%=room_path(room) %>" <% else %> "#" <% end %>>
             <div class="card card-event card-clickable">
              <div class="card-body">
               <h3 class="room-name text-16 no-margin text-warning">
                <%= room.name%>
              </h3> 
              <img src="/assets/default-room.jpg" class="full-width">  
            </div>

            <div class="clickable-button">
              <a class="btn btn-floating btn-red initial-position floating-open">
                <i class="fa fa-ellipsis-h text-white circle-icon"></i></a>
              </div>

              <div class="layered-content bg-red">
                <div class="overflow-content">
                 <h3 class="room-name text-16 font-pacifico">
                  <%= room.name%>
                </h3> 
                <p><%if room.description.present? %>
                  <%= room.description%>
                  <% else%>
                  No descroption present!
                  <% end %>
                </p>
                <p class="font-pacifico float-right"><%=room.user.name%></p><br>
                <h3 class="room-name text-16 font-pacifico">
                  Tags<br>
                </h3>
                <p>
                  <% room.tags.each do |tag| %>
                  <%=tag.name%>

                  <% end %>
                </p>
              </div>
              <div class="clickable-close-button">
                <a class="btn btn-floating initial-position floating-close"><i class="fa fa-close text-white"></i></a>
              </div>
            </div>

          </div>
        </a>
      </div>
      </div>
  <% end %>
  </div>


</div>
</div>
</div>

</div>


</div>
</div>



<script type="text/javascript">
  $( document ).ready(function() {
    /* activate jquery isotope */
    var $container = $('#posts').isotope({
      itemSelector : '.item',
      isFitWidth: true
    });

  // $(window).smartresize(function(){
  //   $container.isotope({
  //     columnWidth: '.col-sm-3'
  //   });
  // });
  
  $container.isotope({ filter: '*' });

    // filter items on button click
    $('#filters').on( 'click', 'button', function() {
      var filterValue = $(this).attr('data-filter');
      $container.isotope({ filter: filterValue });
    });

$container.on( 'layoutComplete',
  function( event, laidOutItems ) {

      if (laidOutItems.length == 0){
        $('.no_room').show();
      }
      else
      {
        $('.no_room').hide();

      }
  }
);

  });



</script>


<script type="text/javascript">
   // window.onload = function(){
// var b_h = $('body').height()
// $('.set_height').css('height',b_h - 200);
// }

// $(window).resize(function(){
// var b_h = $('body').height()
// $('.set_height').css('height',b_h - 200);
// });
float_open();

</script>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<header id="download" class="masthead">
  <div class="container h-100">
    <div class="row h-100">
      <div class="col-lg-7 my-auto">
        <div class="header-content mx-auto">
          <h1 class="mb-5 font-pacifico">D-Radio

          </h1>
          <h2 class="mt-1 font-pacifico list-inline mb-5">online audio calling platform to share your thoughts in English and</h2>
          <% if user_signed_in? %>
          <a data-target="#create_room_modal" data-toggle="modal" class="btn btn-warning text-black btn-xl js-scroll-trigger">Create Your Room</a>
          <!-- <a href="<%=new_room_path%>" class="btn btn-warning text-black btn-xl js-scroll-trigger">Create Your Room</a> -->
          <% else %>
          <a href="https://signup.steemit.com/?ref=d-radio" class="btn btn-warning text-black btn-xl js-scroll-trigger">Sign up with steem</a>
          <% end %>
        </div>
      </div>
      <div class="col-lg-5 my-auto text-center">
        <ul class="rslides list-inline" id="slider1">
          <li><h1 class="font-pacifico">Français</h1></li>
          <li><h1 class="font-pacifico">ગુજરાતી</h1></li>
          <li><h1 class="font-pacifico">客家话</h1></li>
          <li><h1 class="font-pacifico">हिन्दी</h1></li>
          <li><h1 class="font-pacifico">Italiano</h1></li>
          <li><h1 class="font-pacifico">मराठी</h1></li>
          <li><h1 class="font-pacifico">ਪੰਜਾਬੀ</h1></li>                
        </ul>
      </div>
    </div>
  </div>
</header>

<section id="features" class="download bg-primary text-center" id="download">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mx-auto">
        <h2 class="section-heading">About</h2>
        <div class="col-md-8 margin-auto text-center">
          <h3>D-RADIO is the project created to help those people writing and speaking about their life, culture and nationality in their language.</h3>
        </div>
      </div>

    </div>
  </div>
</section>
<section class="download rooms_section text-center padding-top-50" id="liverooms">
  <div class="container ">
    <div class="row">
      <div class="col-md-12 mx-auto">
        <h2 class="section-heading text-40 font-bold text-warning padding-bottom-50">Live Rooms</h2>
        <div class="col-md-12 text-center margin-auto clearfix">
          <% @rooms.last(9).each do |room|%>
          <div class="col-md-4 pull-left">
           <a href= <% if user_signed_in? %> "<%=room_path(room) %>" <% else %> "#" <% end %>>

             <div class="card card-event card-clickable">
              <div class="card-body">
               <h3 class="room-name text-16 no-margin text-warning">
                <%= room.name%>
              </h3> 
              <img src="/assets/default-room.jpg" class="full-width">  
            </div>

            <div class="clickable-button">
              <a class="btn btn-floating btn-red initial-position floating-open">
                <i class="fa fa-ellipsis-h text-white circle-icon"></i></a>
              </div>

              <div class="layered-content bg-red">
                <div class="overflow-content">
                 <h3 class="room-name text-16 font-pacifico">
                  <%= room.name%>
                </h3> 
                <p><%if room.description.present? %>
                  <%= room.description%>
                  <% else%>
                  No descroption present!
                  <% end %>
                </p>
                <p class="font-pacifico float-right"><%=room.user.name%></p><br>
                <h3 class="room-name text-16 font-pacifico">
                  Tags<br>
                </h3>
                <p>
                  <% room.tags.each do |tag| %>
                  <%=tag.name%>

                  <% end %>
                </p>
              </div>
              <div class="clickable-close-button">
                <a class="btn btn-floating initial-position floating-close"><i class="fa fa-close text-white"></i></a>
              </div>
            </div>

          </div>
        </a>
      </div>
      <% end %>

    </div>
  </div>
<h1 class="font-pacifico text-center full-width" style="margin: 40px 0px 0px 0px;"><a href="<%=available_rooms_path%>">View All Rooms</a></h1>
</div>
</div>
</section>
<section class="features">
  <div class="container">
    <div class="section-heading text-center text-white">
      <h2>D-Radio, Fun Radio</h2>
      <p class="text-white">Check out what you can do with the D-Radio!</p>
      <hr>
    </div>

    <div class="row">
      <div class="col-lg-4 my-auto">
        <div class="">
        </div>

      </div>
      <div class="col-lg-8 my-auto">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item ">
                <i class="icon-support text-primary"></i>
                <h3>Account Support</h3>
                <p class="text-muted">Will get support to help you speak with others from the team</p>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-camrecorder text-primary"></i>
                <h3>Recordings</h3>
                <p class="text-muted">Upload/Download your recordings</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-notebook text-primary"></i>
                <h3>Brief About Talk</h3>
                <p class="text-muted">Adding Pictures and a Short Description about what they are talking</p>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="feature-item">
                <i class="icon-globe text-primary"></i>
                <h3>World Wide</h3>
                <p class="text-muted">multiple language with all types of people</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Modal -->
<div class="modal fade" id="create_room_modal" tabindex="-1" role="dialog" aria-labelledby="create_room_modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal-background">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Room</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= render 'form', room: @room %>

    </div>
  </div>
</div>
<%#= link_to 'New Room', new_room_path %>

<script type="text/javascript">
  let api = sc2.Initialize({
    app: 'd-radio-app',
    callbackURL: '<%=LOGIN_URL%>',
    scope: ['']
  })
  var link = api.getLoginURL();
  $('.connect').attr('href', link)

// console.log(link)
// api.me(function (err, res) {
//   console.log(err, res)
// });
float_open();
</script>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<style type="text/css">
footer{position: absolute;
    left: 0;
    bottom: 0;
    height: 100px;
    width: 100%;
    overflow: hidden;}
</style>
<section id="features" class="padding-30 padding-top-100 bg-primary full-height text-center" id="download">
    <div class="share_room">
        <h3>Please share this link to join the talk!</h3>
        <h4><a href="<%=room_path(@room)%>" id="subtitle" class="text-white"></a></h4>
    </div>
</section>
<div id="requirements">
</div>
<div class="col-md-12">
    <section id="roomContainer" class="cf">
        <div class='peerContainer local'>
            <div class="local-details text-center padding-15">
                <!-- <input id="nickInput" placeholder="You"/> -->

                <audio id="localAudio" controls oncontextmenu="return false;" disabled></audio>
                <img id="snapshot" src="<%=current_user.profile_image%>" class="avatar avatar-image"/>
                <div class="">You</div>
                <div id="meters">
                  <div id="instant">
                    <p class="styled">
                        <progress  min="0" max="0.3" value=""></progress>
                    </p>
                    <div class="value" style="display: none;"></div>
                </div>
            </div>
            <video id="snapshotvideo" class="avatar"></video> 
            <a class="btn btn-sm button-mute">Mute</a>
            <div id='countdown'></div>
            <!-- add class of 'muted' when so -->
            

        </div>

        <div class="local-controls">
            <!-- <button class="button button-small" id="snapshotButton">Take a snapshot</button> -->
        </div>
    </div>
    <div id="remotes">
        
    </div>
</section>
</div>


</div>
<script type="text/javascript">
          // grab the room from the URL
          var room;
          room = "<%=params[:id]%>"
          var framed = window.self !== window.top;
          var hasroom = framed && document.referrer && document.referrer.split('?').length > 1;
// if (framed) {
//     room = document.referrer && document.referrer.split('?')[1];
// } else {
//     room = window.parent.location && window.parent.location.search.split('?')[1];
// }

var avatar = '<%=current_user.profile_image%>';
var hasCameras = false;
var nick = '<%=current_user.name%>'
var webrtc;

// for simplistic metrics gathering
function track(name, info) {
    if (webrtc && webrtc.connection) {
        webrtc.connection.emit('metrics', name, info || {});
    }
}

function setRoom(name) {
  
    document.getElementById('subtitle').textContent =  'Join: ' + (framed ? document.referrer + (hasroom ? '' : '?' + name) : window.parent.location.href);
}







function doJoin(room) {
    webrtc.startLocalVideo();
    webrtc.createRoom(room, function (err, name) {
        var newUrl = (framed ? document.referrer : window.parent.location.pathname) + '?' + room;
        if (!err) {
            if (!framed) window.parent.history.replaceState({foo: 'bar'}, null, newUrl);
            setRoom(room);
        } else {
            console.log('error', err, room);
            if (err === 'taken') {
                room = generateRoomName();
                doJoin(room);
            }
        }
    });
}

var queryGum = false;
if (room) {
    setRoom(room);
    queryGum = true;
} else {
 }

function GUM() {
    webrtc = new SimpleWebRTC({
        // we don't do video
        localVideoEl: '',
        remoteVideosEl: '',
        autoRequestMedia: false,
        enableDataChannels: false,
        media: {
            audio: true,
            video: false
        },
        receiveMedia: { // FIXME: remove old chrome <= 37 constraints format
            offerToReceiveAudio: 1,
            offerToReceiveVideo: 0
        },
    });

    webrtc.on('localStream', function(stream) {
        var localAudio = document.getElementById('localAudio');
        localAudio.disabled = false;
        localAudio.volume = 0;
        //localAudio.srcObject = stream; 
        if (hasCameras) {
            document.querySelector('.local-controls').style.visibility = 'visible';
        }

        var track = stream.getAudioTracks()[0];
        var btn = document.querySelector('.local .button-mute');
        btn.style.visibility = 'visible';
        btn.onclick = function() {
            track.enabled = !track.enabled;
            btn.className = 'btn btn-sm button-mute' + (track.enabled ? '' : ' muted');
            if (track.enabled){
                $('.button-mute').text('Mute');
            }
            else{
                $('.button-mute').text('Unmute');
            }
        };
    });

    webrtc.on('readyToCall', function () {
        if (room) {
            
            webrtc.joinRoom(room, function (err, res) {
                if (err) return;
                window.setTimeout(function () {

                    if (avatar) {
                        webrtc.sendToAll('avatar', {avatar: avatar});
                        console.log(avatar);
                    }
                    if (nick) {
                        webrtc.sendToAll('nickname', {nick: nick});
                    }
                }, 1000);
            });
        }
    });

    // working around weird simplewebrtc behaviour
    webrtc.on('videoAdded', function (video, peer) {
        document.querySelector('#container_' + webrtc.getDomId(peer) + '>div.remote-details').appendChild(video);
    });
    // called when a peer is created
    webrtc.on('createdPeer', function (peer) {
        console.log(peer);
        var remotes = document.getElementById('remotes');
        if (!remotes) return;

        var container = document.createElement('div');
        container.className = 'peerContainer';
        container.id = 'container_' + webrtc.getDomId(peer);

        // inner container
        var d = document.createElement('div');
        d.className = 'remote-details padding-15';
        container.appendChild(d);

        

        // avatar profile_image
        var avatar = document.createElement('img');
        avatar.className = 'avatar-image';
        avatar.src = '/assets/avatar-default.png';
        d.appendChild(avatar);
        // // nickname
        var nickname = document.createElement('div');
        nickname.className = 'nick';
        d.appendChild(nickname);
        // audio element
        // inserted later

        // mute button
        var mute = document.createElement('a');
        mute.className = 'btn btn-sm button-mute';
        mute.appendChild(document.createTextNode('Mute'));
        // mute.style.visibility = 'hidden';
        // d.appendChild(mute);

        mute.onclick = function() {
            alert('asfasf');
          if (peer.videoEl.muted) { // unmute
            mute.className = 'btn btn-sm button-mute';
            mute.text('Mute');
          } else { // mute
            mute.className = 'btn btn-sm button-mute muted';
            mute.text('Unmute');
        }
        peer.videoEl.muted = !peer.videoEl.muted;
    };

    if (peer && peer.pc) {
        peer.firsttime = true;
        peer.pc.on('iceConnectionStateChange', function (event) {
            var state = peer.pc.iceConnectionState;
            container.className = 'text-center peerContainer p2p' +
            state.substr(0, 1).toUpperCase() +
            state.substr(1);
            switch (state) {
                case 'connected':
                case 'completed':
                    //audio.srcObject = peer.stream;
                    mute.style.visibility = 'visible';
                    if (peer.firsttime) {
                        peer.firsttime = false;
                        track('iceSuccess', {
                            session: peer.sid,
                            peerprefix: peer.browserPrefix,
                            prefix: webrtc.capabilities.prefix,
                            version: webrtc.capabilities.browserVersion
                        });
                    }
                    break;
                    case 'closed':
                    container.remove();
                    break;
                }
            });
    }
    remotes.appendChild(container);
});

    webrtc.connection.on('message', function (message) {
        var peers = self.webrtc.getPeers(message.from, message.roomType);
        if (!peers && peers.length > 0) return;
        var peer = peers[0];

        // FIXME: also send current avatar and nick to newly joining participants
        var container = document.getElementById('container_' + webrtc.getDomId(peer));
        if (message.type === 'nickname') {
            container.querySelector('.nick').textContent = message.payload.nick;
        } else if (message.type === 'avatar') {
            container.querySelector('.avatar-image').src = message.payload.avatar;
        } else if (message.type === 'offer') {
            // update things
            
            if (avatar) {
                peer.send('avatar', {avatar: avatar});
            }
            if (nick) {
                peer.send('nickname', {nick: nick});
            }
        }
    });

    // local p2p/ice failure
    webrtc.on('iceFailed', function (peer) {
        console.log('local fail', peer.sid);
        track('iceFailed', {
            source: 'local',
            session: peer.sid,
            peerprefix: peer.browserPrefix,
            prefix: webrtc.capabilities.prefix,
            version: webrtc.capabilities.browserVersion
        });
    });

    // remote p2p/ice failure
    webrtc.on('connectivityError', function (peer) {
        console.log('remote fail', peer.sid);
        track('iceFailed', {
            source: 'remote',
            session: peer.sid,
            peerprefix: peer.browserPrefix,
            prefix: webrtc.capabilities.prefix,
            version: webrtc.capabilities.browserVersion
        });
    });

    if (!(navigator && navigator.mediaDevices && navigator.mediaDevices.getUserMedia && window.RTCPeerConnection)) {
        // FIXME: show "sorry, get a modern browser" (recommending Edge)
        document.getElementById('supportWarning').style.display = 'block';
        document.querySelector('form#createRoom>button').disabled = true;
    } else if (navigator && navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {
        navigator.mediaDevices.enumerateDevices()
        .then(function (devices) {
            var cameras = devices.filter(function(device) { return device.kind === 'videoinput'; });
            hasCameras = cameras.length;
            var mics = devices.filter(function(device) { return device.kind === 'audioinput'; });
            if (mics.length) {
                document.getElementById('requirements').style.display = 'none';
                if (queryGum) webrtc.startLocalVideo();
            } else {
                document.getElementById('microphoneWarning').style.display = 'block';
                document.querySelector('form#createRoom>button').disabled = true;
            }
        });
    }
}

$(document).ready(function(){
//     GUM();
// })

// window.onload =  function(){
 GUM();
 callaudio();
});
function createFields() {
    $('.field').remove();
    var container = $('#container');
    for(var i = 0; i < +$('input:text').val(); i++) {
        $('<div/>', {
            'class': 'field',
            'text': i + 1
        }).appendTo(container);
    }
}

function distributeFields() {
    var radius = 200;
    var fields = $('.field'), container = $('#container'),
    width = container.width(), height = container.height(),
    angle = 0, step = (2*Math.PI) / fields.length;
    fields.each(function() {
        var x = Math.round(width/2 + radius * Math.cos(angle) - $(this).width()/2);
        var y = Math.round(height/2 + radius * Math.sin(angle) - $(this).height()/2);
        if(window.console) {
            console.log($(this).text(), x, y);
        }
        $(this).css({
            left: x + 'px',
            top: y + 'px'
        });
        angle += step;
    });
}

$('input').change(function() {
    createFields();
    distributeFields();
});

createFields();
distributeFields();
</script>