config/routes.rb
Rails.application.routes.draw do
    mount Resque::Server, :at => '/resque'
  get 'dradio_widget', to: 'rooms#widget', as: :widget
	get 'available_rooms', to: 'rooms#available_rooms', as: :available_rooms
	root 'rooms#index'
  resources :rooms
 scope module: :users do
        devise_for :users, skip: [:passwords, :registrations]
      end
devise_scope :user do
      get 'auth/login', to: 'users/sessions#custom_login', as: :login
    end
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>DRadio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= javascript_include_tag 'application' %>
  </head>

  <body id="page-top">
    <% if !current_page?(widget_path) %>
    <% if current_page?(available_rooms_path) %>
      <% nav_class = 'bg-change'%>
      <% end %>
    <!-- NAVBAR STARTS -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top <%=nav_class%>" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger font-pacifico" href="<%=root_path%>" >
          D Radio
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <% if !current_page?(available_rooms_path) %>

            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="<%=root_path%>">HOME</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#features">ABOUT</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#liverooms">Live Rooms</a>
            </li>
            <% end %>
            <li class="nav-item">
              <% if user_signed_in? %>
                <%=link_to 'Sign Out', destroy_user_session_path, method: :delete ,class: 'nav-link js-scroll-trigger'%>
              <% else %>
                <a class="nav-link js-scroll-trigger connect" href="#contact">STEEM-LOGIN</a>
              <%end%>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <% end %>
    <!-- NAVBAR STARTS -->
    <%= yield %>
    <div id="js-heightControl" style="height: 0;">&nbsp;</div>
    <% if !current_page?(widget_path) %>
    
    <footer>
      <div class="container">
        <p>&copy; D-Radio 2018. All Rights Reserved.</p>
       <!--  <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#">FAQ</a>
          </li>
        </ul> -->
      </div>
    </footer>
    <% end %>
    <%= javascript_include_tag 'application_postyield' %>
<script>
   $(function(){
       $('#js-heightControl').css('height', $(window).height() - $('html').height() +'px');
   });
</script>

<script type="text/javascript">


 <%- flash.each do |name, msg| -%>
 <% if msg.is_a?(String) %>
 $(document).ready(function() {
  toastr.options = {
    closeButton: true,
    progressBar: true,
    showMethod: 'slideDown',
    timeOut: 9000
  };
            // green
            <% if name=="notice" %>
            toastr.success('<%= msg %>');
            // yellow
            <% elsif name=="warning" %>
            toastr.warning('<%= msg %>');
            // red 
            <% elsif name=="alert" %>
            <% if msg.blank? %>
            <% else %>
            toastr.error('<%= msg %>'); 
            <% end %>
             //blue 
             <% elsif name=="info" %>
             toastr.info('<%= msg %>');
             <% end %>
           }); 
 <%- end -%>
 <% end %> 
</script>
  </body>
</html>